apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-config-server
  name: demo-config-server
  namespace: demo-config-ns
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: demo-config-server

